/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.paper2d;

@:umodule("Paper2D")
@:glueCppIncludes("PaperFlipbook.h")
@:uextern extern class FPaperFlipbookKeyFrame {
  @:uname('new') public static function create():PHaxeCreated<unreal.paper2d.FPaperFlipbookKeyFrame>;
  public var FrameRun : unreal.Int32;
  public var Sprite : unreal.paper2d.UPaperSprite;
  
}
