/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.aimodule;

@:umodule("AIModule")
@:glueCppIncludes("EnvironmentQuery/EnvQueryTest.h")
@:uextern extern class FAIDataProviderFloatValue extends unreal.aimodule.FAIDataProviderTypedValue {
  @:uname('new') public static function create():PHaxeCreated<unreal.aimodule.FAIDataProviderFloatValue>;
  public var DefaultValue : unreal.Float32;
  
}
