/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.custommeshcomponent;


/**
  Component that allows you to specify custom triangle mesh geometry
**/
@:umodule("CustomMeshComponent")
@:glueCppIncludes("CustomMeshComponent.h")
@:uextern extern class UCustomMeshComponent extends unreal.UMeshComponent {
  
  /**
    Removes all geometry from this triangle mesh.  Does not deallocate memory, allowing new geometry to reuse the existing allocation.
  **/
  @:final public function ClearCustomMeshTriangles() : Void;
  
}
