/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeinit;


/**
  This class is only here to make sure we're visible to UHT.
  We need to be visible to UHT so that UE4HaxeExternGenerator works correctly
  (as any script generator must return a module name that is visible to UHT)
  see IScriptGeneratorPluginInterface::GetGeneratedCodeModuleName for the related code
**/
@:umodule("HaxeInit")
@:glueCppIncludes("Private/StubUObject.h", "Engine.h")
@:uextern extern class UObjectStub extends unreal.UObject {
  
}
