/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.proceduralmeshcomponent;


/**
  Component that allows you to specify custom triangle mesh geometry
  Beware! This feature is experimental and may be substantially changed in future releases.
**/
@:umodule("ProceduralMeshComponent")
@:glueCppIncludes("ProceduralMeshComponent.h")
@:uextern extern class UProceduralMeshComponent extends unreal.UMeshComponent {
  
  /**
    Clear a section of the procedural mesh. Other sections do not change index.
  **/
  @:final public function ClearMeshSection(SectionIndex : unreal.Int32) : Void;
  
  /**
    Clear all mesh sections and reset to empty state
  **/
  @:final public function ClearAllMeshSections() : Void;
  
  /**
    Control visibility of a particular section
  **/
  @:final public function SetMeshSectionVisible(SectionIndex : unreal.Int32, bNewVisibility : Bool) : Void;
  
  /**
    Returns whether a particular section is currently visible
  **/
  @:thisConst @:final public function IsMeshSectionVisible(SectionIndex : unreal.Int32) : Bool;
  
  /**
    Collision data
  **/
  public var ProcMeshBodySetup : unreal.UBodySetup;
  // Interface_CollisionDataProvider interface implementation
  
}
