/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.html5platformeditor;

@:umodule("HTML5PlatformEditor")
@:glueCppIncludes("Private/HTML5SDKSettings.h")
@:uextern extern class FHTML5DeviceMapping {
  @:uname('new') public static function create():PHaxeCreated<unreal.html5platformeditor.FHTML5DeviceMapping>;
  public var DevicePath : unreal.FFilePath;
  public var DeviceName : unreal.FString;
  
}
