/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeunittests;

@:umodule("HaxeUnitTests")
@:glueCppIncludes("TestUseEnum.h")
@:uname("ETestHxEnumClass")
@:class @:uextern extern enum ETestHxEnumClass {
  
  /**
    SecondOne
  **/
  @DisplayName("SecondOne")
  E_2nd;
  
  /**
    ThirdOne
  **/
  @DisplayName("ThirdOne")
  E_3rd;
  
  /**
    FirstOne
  **/
  @DisplayName("FirstOne")
  E_1st;
  
}
