/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.haxeunittests;

@:umodule("HaxeUnitTests")
@:glueCppIncludes("BasicTypesUObject.h")
@:uextern extern class UBasicTypesUObject extends unreal.UObject {
  private var m_FStringProp : unreal.FString;
  public var doubleProp : unreal.Float64;
  public var floatProp : unreal.Float32;
  public var ui64Prop : unreal.FakeUInt64;
  public var i64Prop : unreal.Int64;
  public var ui32Prop : unreal.FakeUInt32;
  public var i32Prop : unreal.Int32;
  public var i16Prop : unreal.Int16;
  public var ui16Prop : unreal.UInt16;
  public var i8Prop : unreal.Int8;
  public var ui8Prop : unreal.UInt8;
  public var stringProp : unreal.FString;
  public var boolProp : Bool;
  @:final public function getBoolProp() : Bool;
  @:final public function getStringProp() : unreal.FString;
  @:final public function getUi8Prop() : unreal.UInt8;
  @:final public function getI8Prop() : unreal.Int8;
  @:final public function getI32Prop() : unreal.Int32;
  @:final public function getUi32Prop() : unreal.FakeUInt32;
  @:final public function getI64Prop() : unreal.Int64;
  @:final public function getFloatProp() : unreal.Float32;
  @:final public function getDoubleProp() : unreal.Float64;
  @:final public function setBool_String_UI8_I8(b : Bool, str : unreal.FString, ui8 : unreal.UInt8, i8 : unreal.Int8) : unreal.haxeunittests.UBasicTypesUObject;
  private function setBool_String_UI8_I8_protected(b : Bool, str : unreal.FString, ui8 : unreal.UInt8, i8 : unreal.Int8) : unreal.haxeunittests.UBasicTypesUObject;
  
}
