/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeunittests;

@:umodule("HaxeUnitTests")
@:glueCppIncludes("BasicTypesSub.h", "Engine.h")
@:uextern extern class UBasicTypesSub2 extends unreal.haxeunittests.UBasicTypesUObject implements unreal.haxeunittests.IBasicType2 {
  
}
