/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeunittests;


/**
  added as workaround for UHT, otherwise it won't recognize this file.
**/
@:umodule("HaxeUnitTests")
@:glueCppIncludes("FDelHaxe5.h")
@:uextern extern class UFDelHaxe5__Dummy extends unreal.UObject {
  
}
