/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeunittests;


/**
  WARNING! This file was autogenerated by:
   _   _ _____     ___   _   _ __   __
  | | | |  ___|   /   | | | | |\ \ / /
  | | | | |__    / /| | | |_| | \ V /
  | | | |  __|  / /_| | |  _  | /   \
  | |_| | |___  \___  | | | | |/ /^\ \
   \___/\____/      |_/ \_| |_/\/   \/
**/
@:umodule("HaxeUnitTests")
@:glueCppIncludes("HaxeDerived1.h")
@:uextern extern class UHaxeDerived1 extends unreal.haxeunittests.UBasicTypesSub1 {
  public var subclassArray : unreal.TArray<unreal.TSubclassOf<unreal.haxeunittests.UHaxeDerived2>>;
  public var subclass : unreal.TSubclassOf<unreal.haxeunittests.UHaxeDerived2>;
  public var intProp : unreal.Int32;
  public var protectedFName : unreal.FName;
  public var someFName : unreal.FName;
  
}
