/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.haxeunittests;


/**
  WARNING! This file was autogenerated by:
   _   _ _____     ___   _   _ __   __
  | | | |  ___|   /   | | | | |\ \ / /
  | | | | |__    / /| | | |_| | \ V /
  | | | |  __|  / /_| | |  _  | /   \
  | |_| | |___  \___  | | | | |/ /^\ \
   \___/\____/      |_/ \_| |_/\/   \/
**/
@:umodule("HaxeUnitTests")
@:glueCppIncludes("HaxeDerived1.h")
@:uextern extern class UHaxeDerived1 extends unreal.haxeunittests.UBasicTypesSub1 {
  public function uFunction1() : unreal.Int32;
  public function uFunction5() : unreal.FName;
  public function returnsItself() : unreal.haxeunittests.UHaxeDerived1;
  public function uFunction3(delta : unreal.Float32) : Void;
  public function uFunctionNameChanged2(delta : unreal.Float32) : Void;
  public function uFunctionNameChanged() : unreal.Int32;
  public function uFunction4() : Void;
  public function TestFName(i32 : unreal.Int32, fname : unreal.FName) : Void;
  public var subclassArray : unreal.TArray<unreal.TSubclassOf<unreal.haxeunittests.UHaxeDerived2>>;
  public var subclass : unreal.TSubclassOf<unreal.haxeunittests.UHaxeDerived2>;
  public var intProp : unreal.Int32;
  public var protectedFName : unreal.FName;
  public var someFName : unreal.FName;
  
}
