/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.haxeunittests;


/**
  WARNING! This file was autogenerated by:
   _   _ _____     ___   _   _ __   __
  | | | |  ___|   /   | | | | |\ \ / /
  | | | | |__    / /| | | |_| | \ V /
  | | | |  __|  / /_| | |  _  | /   \
  | |_| | |___  \___  | | | | |/ /^\ \
   \___/\____/      |_/ \_| |_/\/   \/
**/
@:umodule("HaxeUnitTests")
@:glueCppIncludes("HaxeDerived3.h", "Engine.h")
@:uextern extern class UHaxeDerived3 extends unreal.haxeunittests.UHaxeDerived2 {
  
}
