/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Keyframe position data for one track.  Pos(i) occurs at Time(i).  Pos.Num() always equals Time.Num().
**/
@:glueCppIncludes("Animation/AnimSequenceBase.h", "Engine.h")
@:uextern extern class FAnimNotifyTrack {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimNotifyTrack>;
  public var TrackColor : unreal.FLinearColor;
  public var TrackName : unreal.FName;
  
}
