/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Information about an animation asset that needs to be ticked
**/
@:glueCppIncludes("Animation/AnimInstance.h")
@:uextern extern class FAnimTickRecord {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimTickRecord>;
  public var SourceAsset : unreal.UAnimationAsset;
  
}
