/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  This represents a baked transition
**/
@:glueCppIncludes("AnimGraphNode_TwoWayBlend.h", "Engine.h")
@:uextern extern class FAnimationNode_TwoWayBlend extends unreal.FAnimNode_Base {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimationNode_TwoWayBlend>;
  public var AlphaScaleBias : unreal.FInputScaleBias;
  public var Alpha : unreal.Float32;
  public var B : unreal.FPoseLink;
  public var A : unreal.FPoseLink;
  
}
