/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Blend list node; has many children
**/
@:glueCppIncludes("AnimGraphNode_BlendListByInt.h")
@:uextern extern class FAnimNode_BlendListByInt extends unreal.FAnimNode_BlendListBase {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimNode_BlendListByInt>;
  public var ActiveChildIndex : unreal.Int32;
  
}
