/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  This is the base class that both baked states and transitions use
**/
@:glueCppIncludes("Animation/AnimBlueprintGeneratedClass.h", "Engine.h")
@:uextern extern class FAnimationStateBase {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimationStateBase>;
  
  /**
    The name of this state
  **/
  public var StateName : unreal.FName;
  
}
