/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Animation/AnimBlueprint.h", "Engine.h")
@:uextern extern class FAnimParentNodeAssetOverride {
  @:uname('new') public static function create():PHaxeCreated<unreal.FAnimParentNodeAssetOverride>;
  public var ParentNodeGuid : unreal.FGuid;
  public var NewAsset : unreal.UAnimationAsset;
  
}
