/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Information for one event in the track.
**/
@:glueCppIncludes("Matinee/InterpTrackBoolProp.h", "Engine.h")
@:uextern extern class FBoolTrackKey {
  @:uname('new') public static function create():PHaxeCreated<unreal.FBoolTrackKey>;
  public var Value : Bool;
  public var Time : unreal.Float32;
  
}
