/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Abilities/GameplayAbilityTargetActor_Trace.h")
@:uextern extern class FCollisionProfileName {
  @:uname('new') public static function create():PHaxeCreated<unreal.FCollisionProfileName>;
  public var Name : unreal.FName;
  
}
