/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  A vector parameter
**/
@:glueCppIncludes("Materials/MaterialParameterCollection.h", "Engine.h")
@:uextern extern class FCollectionVectorParameter extends unreal.FCollectionParameterBase {
  @:uname('new') public static function create():PHaxeCreated<unreal.FCollectionVectorParameter>;
  public var DefaultValue : unreal.FLinearColor;
  
}
