/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Engine/InheritableComponentHandler.h", "Engine.h")
@:uextern extern class FComponentOverrideRecord {
  @:uname('new') public static function create():PHaxeCreated<unreal.FComponentOverrideRecord>;
  public var ComponentKey : unreal.FComponentKey;
  public var ComponentTemplate : unreal.UActorComponent;
  
}
