/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Debug property display functionality to interact with this, use "display", "displayall", "displayclear"
  
  @see UGameViewportClient
  @see FDebugDisplayProperty
  @see DrawStatsHUD
**/
@:glueCppIncludes("Engine/GameViewportClient.h", "Engine.h")
@:uextern extern class FDebugDisplayProperty {
  @:uname('new') public static function create():PHaxeCreated<unreal.FDebugDisplayProperty>;
  
  /**
    if Obj is a class and WithinClass is not nullptr, further limit the display to objects that have an Outer of WithinClass
  **/
  public var WithinClass : unreal.TSubclassOf<unreal.UObject>;
  
  /**
    the object whose property to display. If this is a class, all objects of that class are drawn.
  **/
  public var Obj : unreal.UObject;
  
}
