/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Each elements in the grid
**/
@:glueCppIncludes("Animation/BlendSpaceBase.h", "Engine.h")
@:uextern extern class FEditorElement {
  @:uname('new') public static function create():PHaxeCreated<unreal.FEditorElement>;
  
  /**
    MAX_VERTICES @fixmeconst
  **/
  public var Weights : unreal.Float32;
  public var Indices : unreal.Int32;
  
}
