/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Animation/AnimSequenceBase.h")
@:uextern extern class FFloatCurve extends unreal.FAnimCurveBase {
  @:uname('new') public static function create():PHaxeCreated<unreal.FFloatCurve>;
  
  /**
    Curve data for float.
  **/
  public var FloatCurve : unreal.FRichCurve;
  
}
