/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Components/InstancedStaticMeshComponent.h", "Engine.h")
@:uextern extern class FInstancedStaticMeshInstanceData {
  @:uname('new') public static function create():PHaxeCreated<unreal.FInstancedStaticMeshInstanceData>;
  public var ShadowmapUVBias : unreal.FVector2D;
  public var LightmapUVBias : unreal.FVector2D;
  public var Transform : unreal.FMatrix;
  
}
