/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Sphere shape used for collision
**/
@:glueCppIncludes("PhysicsEngine/BodySetup.h", "Engine.h")
@:uextern extern class FKSphereElem extends unreal.FKShapeElem {
  @:uname('new') public static function create():PHaxeCreated<unreal.FKSphereElem>;
  public var Radius : unreal.Float32;
  public var Center : unreal.FVector;
  public var TM_DEPRECATED : unreal.FMatrix;
  
}
