/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Particles/ParticleSystem.h", "Engine.h")
@:uextern extern class FNamedEmitterMaterial {
  @:uname('new') public static function create():PHaxeCreated<unreal.FNamedEmitterMaterial>;
  public var Material : unreal.UMaterialInterface;
  public var Name : unreal.FName;
  
}
