/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Struct that contains one entry for an 'event' during the timeline
**/
@:glueCppIncludes("Components/TimelineComponent.h", "Engine.h")
@:uextern extern class FTimelineEventEntry {
  @:uname('new') public static function create():PHaxeCreated<unreal.FTimelineEventEntry>;
  
  /**
    Time at which event should fire
  **/
  public var Time : unreal.Float32;
  
}
