/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  This defines what constraint it is defined
**/
@:glueCppIncludes("Animation/Rig.h", "Engine.h")
@:uextern extern class FTransformBaseConstraint {
  @:uname('new') public static function create():PHaxeCreated<unreal.FTransformBaseConstraint>;
  
  /**
    What transform type *
  **/
  public var TransformConstraints : unreal.TArray<unreal.FRigTransformConstraint>;
  
}
