/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  Implements the Editor's user settings.
**/
@:glueCppIncludes("Tests/AutomationTestSettings.h")
@:uextern extern class UAutomationTestSettings extends unreal.UObject {
  
  /**
    Folders containing levels to exclude from automated tests
  **/
  public var TestLevelFolders : unreal.TArray<unreal.FString>;
  
  /**
    Modules to load that have editor tests
  **/
  public var EditorTestModules : unreal.TArray<unreal.FString>;
  
  /**
    Modules to load that have engine tests
  **/
  public var EngineTestModules : unreal.TArray<unreal.FString>;
  
}
