/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  BodySetup contains all collision information that is associated with a single asset.
  A single BodySetup instance is shared among many BodyInstances so that geometry data is not duplicated.
  Assets typically implement a GetBodySetup function that is used during physics state creation.
  
  @see GetBodySetup
  @see FBodyInstance
**/
@:glueCppIncludes("PhysicsEngine/BodySetup.h")
@:uextern extern class UBodySetup extends unreal.UObject {
  
}
