/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  A DamageType is intended to define and describe a particular form of damage and to provide an avenue
  for customizing responses to damage from various sources.
  
  For example, a game could make a DamageType_Fire set it up to ignite the damaged actor.
  
  DamageTypes are never instanced and should be treated as immutable data holders with static code
  functionality.  They should never be stateful.
**/
@:glueCppIncludes("GameFramework/DamageType.h")
@:uextern extern class UDamageType extends unreal.UObject {
  
}
