/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Kismet/KismetInputLibrary.h")
@:uextern extern class UKismetInputLibrary extends unreal.UBlueprintFunctionLibrary {
  
  /**
    Calibrate the tilt for the input device
  **/
  static public function CalibrateTilt() : Void;
  
  /**
    Test if the input key are equal (A == B)
    @param A - The key to compare against
    @param B - The key to compare
    @returns True if the key are equal, false otherwise
  **/
  static public function EqualEqual_KeyKey(A : unreal.inputcore.FKey, B : unreal.inputcore.FKey) : Bool;
  
  /**
    @returns True if the key is a modifier key: Ctrl, Command, Alt, Shift
  **/
  static public function Key_IsModifierKey(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
  /**
    @returns True if the key is a gamepad button
  **/
  static public function Key_IsGamepadKey(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
  /**
    @returns True if the key is a mouse button
  **/
  static public function Key_IsMouseButton(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
  /**
    @returns True if the key is a keyboard button
  **/
  static public function Key_IsKeyboardKey(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
  /**
    @returns True if the key is a float axis
  **/
  static public function Key_IsFloatAxis(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
  /**
    @returns True if the key is a vector axis
  **/
  static public function Key_IsVectorAxis(Key : unreal.Const<unreal.PRef<unreal.inputcore.FKey>>) : Bool;
  
}
